spring.datasource:
  platform: h2
  username: sa
  password:
  driverClassName: org.h2.Driver
  hikari:
    connection-init-sql: CREATE SCHEMA IF NOT EXISTS event
spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      show_sql: true
      use_sql_comments: false
      format_sql: true
#Security Settings
spring.security:
  user:
    name:  xcats
    password: Xcatsteam191
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:/var/db/test;DB_CLOSE_ON_EXIT=TRUE
  h2:
    console:
      enabled: true
      path: /console
management:
  security:
    enabled: false
security:
  basic:
    enabled: false
---
spring.profiles: deploy
server.port: 80
---
spring:
  profiles: prod
  datasource:
    url: jdbc:h2:/var/db/production;DB_CLOSE_ON_EXIT=TRUE
