spring:
  #Database Settings
  datasource:
    url: jdbc:h2:/var/db/test;DB_CLOSE_ON_EXIT=TRUE;INIT= CREATE SCHEMA IF NOT EXISTS event
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

  #Security Settings
  security:
    user:
      name:  xcats
      password: Xcatsteam191

