spring.datasource:
  platform: h2
  username: sa
  password:
  driverClassName: org.h2.Driver
spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      show_sql: true
      use_sql_comments: false
      format_sql: true
#Security Settings
spring.security:
  user:
    name:  xcats
    password: Xcatsteam191
---
spring:
  profiles: deploylocal
  datasource:
    url: jdbc:h2:/var/db/test;DB_CLOSE_ON_EXIT=TRUE;INIT= CREATE SCHEMA IF NOT EXISTS event
  h2:
    console:
      enabled: true
server:
  address: 127.0.0.1
  port: 80
---
spring:
  profiles: deploydev
  datasource:
      url: jdbc:h2:/var/db/test;DB_CLOSE_ON_EXIT=TRUE;INIT= CREATE SCHEMA IF NOT EXISTS event
  h2:
    console:
      enabled: true
server:
  port: 80
  address: 127.0.0.1 #dev.xscout.org
---
spring:
  profiles: deployproduction
  datasource:
    url: jdbc:h2:/var/db/production;DB_CLOSE_ON_EXIT=TRUE;INIT= CREATE SCHEMA IF NOT EXISTS event
server:
  port: 80
  address: www.xscout.org

